from app.chatbot.service import MedicalAssistance

class FakeLLM:
    """
    Fake LLM class to simulate the behavior of the LLM for testing purposes.
    """
    def generate(self, messages):
        return "RESPUESTA_FAKE"


class FakeRetriever:
    """
    Fake Retriever class to simulate the behavior of the Retriever for testing purposes.
    """
    def retrieve(self, query):
        return "CONTEXTO_FAKE"


def test_service_returns_llm_response():
    """
    Check that the service returns the response generated by the LLM.
    """
    # Create the bot with the fake LLM and Retriever (Arrange)
    llm = FakeLLM()
    retriever = FakeRetriever()

    bot = MedicalAssistance(
        llm=llm,
        retriever=retriever,
    )

    # Get the response from the bot (Act)
    # As it is a fake retriever, it does not matter the content 
    # of the query, it will always return the same context, and
    # the fake LLM will always return the same response.
    response = bot.generate_response(
        [{"role": "user", "content": "Tengo fiebre"}]
    )

    # Check that the response is the expected one (Assert)
    assert response == "RESPUESTA_FAKE"