from app.chatbot.service import MedicalAssistance

class FakeLLM:
    """
    Fake LLM class to simulate the behavior of the LLM for testing purposes.
    """
    def __init__(self):
        self.received_messages = None

    def generate(self, messages):
        self.received_messages = messages
        return "RESPUESTA_FAKE"


class FakeRetriever:
    """
    Fake Retriever class to simulate the behavior of the Retriever for testing purposes.
    """
    def __init__(self):
        self.received_query = None

    def retrieve(self, query):
        self.received_query = query
        return "CONTEXTO_FAKE"

class FakeEmptyRetriever:
    """
    Fake Retriever that simulates no relevant context being found.
    """
    def retrieve(self, query):
        return None
    
def test_service_returns_llm_response():
    """
    Check that the service returns the response generated by the LLM.
    """
    # Create the bot with the fake LLM and Retriever (Arrange)
    llm = FakeLLM()
    retriever = FakeRetriever()

    bot = MedicalAssistance(
        llm=llm,
        retriever=retriever,
    )

    # Get the response from the bot (Act)
    # As it is a fake retriever, it does not matter the content 
    # of the query, it will always return the same context, and
    # the fake LLM will always return the same response.
    response = bot.generate_response(
        [{"role": "user", "content": "Tengo fiebre"}]
    )

    # Check that the response is the expected one (Assert)
    assert response == "RESPUESTA_FAKE"

def test_service_uses_retrieved_context():
    """
    Check that the service uses the retrieved context.
    """
    llm = FakeLLM()
    retriever = FakeRetriever()

    bot = MedicalAssistance(
        llm=llm,
        retriever=retriever,
    )

    bot.generate_response(
        [{"role": "user", "content": "Tengo fiebre"}]
    )

    # Check that the retrieved context is included in the messages sent to the LLM
    assert "CONTEXTO_FAKE" in llm.received_messages[1]["content"]
    # Check that the original user message is also included in the messages sent to the LLM
    assert "Tengo fiebre" in llm.received_messages[1]["content"]

def test_service_uses_fallback_when_no_context_is_found():
    """
    Check that the service uses a fallback when no relevant context is found.
    """
    llm = FakeLLM()
    retriever = FakeEmptyRetriever()

    bot = MedicalAssistance(
        llm=llm,
        retriever=retriever,
    )

    bot.generate_response(
        [{"role": "user", "content": "Tengo un síntoma desconocido"}]
    )

    # Check that the fallback message is included in the messages sent to the LLM
    assert "Lo siento, no hay información al respecto" in llm.received_messages[1]["content"]
    # Check that the original user message is included in the messages sent to the LLM
    assert "Tengo un síntoma desconocido" in llm.received_messages[1]["content"]

def test_service_sends_user_query_to_retriever():
    """
    Check that the service sends the user's query to the retriever.
    """
    llm = FakeLLM()
    retriever = FakeRetriever()

    bot = MedicalAssistance(
        llm=llm,
        retriever=retriever,
    )

    bot.generate_response(
        [{"role": "user", "content": "Tengo fiebre"}]
    )
    # Check that the retriever received the correct user query
    assert retriever.received_query == "Tengo fiebre"