from fastapi import FastAPI

from app.schemas import ChatRequest


def create_app(bot):
    """
    Factory function to create a FastAPI app with the given bot instance.
    """
    app = FastAPI()

    @app.get("/health")
    def health():
        """
        Health check endpoint to verify that the API is running.
        """
        return {"status": "ok"}

    @app.post("/predict")
    def predict(request: ChatRequest):
        """
        Predict endpoint that takes a chat request and returns a response generated by the bot.
        """
        chat_history_dicts = [
            message.model_dump()
            for message in request.messages
        ]

        response = bot.generate_response(chat_history_dicts)

        return {"response": response}

    return app