import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

class QwenLLM:
    """
    Class that manage the llm.

    It receives a message and gives the response.
    """
    def __init__(
            self,
            model_name: str = "Qwen/Qwen2.5-0.5B-Instruct",
            ):
        """
        Initialize a new llm.

        Attributes
        ----------
        model_name : obj
            The model of LLM (or SLM) used.

        """
        # Use GPU if available
        # self.device = "cuda" if torch.cuda.is_available() else "cpu"
        # Use CPU for Docker
        self.device = "cpu"
        # torch.set_num_threads(4)

        # Defined the model to use
        self.model_name = model_name

        # Load the tokenizer and the model
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        
        # If GPU:
        # self.model = AutoModelForCausalLM.from_pretrained(
        #     model_name,
        #     dtype="auto",
        #     device_map="auto"
        # )
        # Forced Float32 and cpu for Docker
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            dtype=torch.float32,
            device_map=self.device,
            low_cpu_mem_usage=True,
        )
        self.model.eval()

    def generate(self, messages: list[dict[str, str]]) -> str:
        """
        Performs the llm work: Generates a response given the messages.

        Parameters
        ----------
        messages : List[Dict[str, str]]
            Conversation history containing user and assistant messages.
        
        Returns
        -------
        response : str
            The response generated by the assistant.

        """
        # Apply chat template
        text = self.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )

        # Tokenize
        inputs = self.tokenizer(
            [text],
            return_tensors="pt",
        ).to(self.device)

        # Generate the output
        outputs = self.model.generate(
            **inputs,
            max_new_tokens=256,
            do_sample=True,
            temperature=0.1,
            top_p=0.9,
        )

        # Decode the new response
        response = self.tokenizer.decode(
            outputs[0][inputs.input_ids.shape[1] :], 
            skip_special_tokens=True,
        )
        return response.strip()
    
