"""
Module containing the MedicalAssistance class.

Classes:
    - MedicalAssistance: Class that represents a chatbot for medical assistance.
"""

from typing import List, Dict

class MedicalAssistance:
    """
    Class that represents a chatbot for medical assistance.

    This class handles the chatbot to generate responses.
    """

    def __init__(
            self,
            llm,
            retriever,
            ):
        """
        Initialize a new bot.

        Attributes
        ----------
        llm : obj
            The llm we use to generate responses given the messages.
        retriever : obj
            The retriever used to manage the messages.
        """
        self.llm = llm
        self.retriever = retriever

    def generate_response(self, chat_history: List[Dict[str, str]]):
        """
        Generate a response given the chat history and the medical context.

        This method performs:
        1. Semantic retrieval using the injected retriever
        2. Prompt construction
        3. LLM generative inference
        Parameters
        ----------
        chat_history : List[Dict[str, str]]
            Conversation history containing user and assistant messages.

        Returns
        -------
        response : str
            The response generated by the assistant.

        Notes
        -----
        The chat history is expected to follow this structure:
        [{"role": "user", "content": "Hola"},
        {"role": "assistant", "content": "Hola..."}]

        In this model we use a lightweight RAG pipeline over a plain text knowledge
        base. It is intentionally kept simple to allow fast iteration, and can be
        extended later if needed.
        """

        # Get the last query
        last_user_message = chat_history[-1]["content"]

        # RAG: Search only the relevant information
        relevant_info = self.retriever.retrieve(last_user_message)

        if relevant_info:
            context_to_use = relevant_info
        else:
            context_to_use = (
                "No hay información específica en la base de datos."
                "Respuesta obligatoria: Lo siento, no hay información al respecto."
            )
        # print("CONTEXTO: ", context_to_use)
        full_prompt = f"""
        Instrucciones: Eres un asistente médico.
        Responde DIRECTAMENTE al paciente (usa "usted") basándote SOLO en el TEXTO OFICIAL.
        Usa oraciones completas.
        Sé empático con el paciente.

        TEXTO OFICIAL:
        {context_to_use}

        ---
        PREGUNTA DEL PACIENTE: {last_user_message}
        
        TU RESPUESTA AL PACIENTE:
        """

        # Message structure
        messages = [
            {"role": "system", "content": "Eres un asistente médico útil y preciso."},
            {"role": "user", "content": full_prompt},
        ]

        response = self.llm.generate(messages)

        return response
